module.exports = {
    products: [
        {
            _id: 1,
            name: 'PVC Pipes',
            category: 'PVC',
            image: './images/pvc pipes.jpg',
            price: 797000,
            brand: 'Lonfa',
            rating: 5.5,
            numReviews: 10,
            countInStock: 120
        },
        {
            _id: 2,
            name: 'Facia boards',
            category: 'PVC',
            image: './images/facia board.jpg',
            price: 70000,
            brand: 'Hua Sheng',
            rating: 3.9,
            numReviews: 5,
            countInStock: 1000
        },
        {
            _id: 3,
            name: 'Hose Pipes',
            category: 'PVC',
            image: './images/horse pipes.jpg',
            price: 500000,
            brand: 'Hua Sheng',
            rating: 4.5,
            numReviews: 21,
            countInStock: 80
        },
        {
            _id: 4,
            name: 'Water Tank',
            category: 'PVC',
            image: './images/water tank.png',
            price: 65000,
            brand: 'Hua Sheng',
            rating: 5,
            numReviews: 101,
            countInStock: 120
        },
        {
            _id: 5,
            name: 'Support',
            category: 'PVC',
            image: './images/support.jpg',
            price: 120000,
            brand: 'Hua Sheng',
            rating: 5,
            numReviews: 120,
            countInStock: 600
        },
        {
            _id: 6,
            name: 'Shelf Brackets',
            category: 'PVC',
            image: './images/shelf brackets.jpg',
            price: 6000,
            brand: 'Hua Sheng',
            rating: 3.5,
            numReviews: 100,
            countInStock: 2000
        },
        {
            _id: 7,
            name: 'HDPE Pipes',
            category: 'PVC',
            image: './images/hdpe.jpg',
            price: 6000,
            brand: 'Hua Sheng',
            rating: 3.5,
            numReviews: 100,
            countInStock: 2000
        },
        {
            _id: 8,
            name: 'Pipe Fittings',
            category: 'PVC',
            image: './images/pipe fittings.jpg',
            price: 55000,
            brand: 'Hua Sheng',
            rating: 5.5,
            numReviews: 10,
            countInStock: 120
        },
        {
            _id: 9,
            name: 'Gutters',
            category: 'PVC',
            image: './images/gutters.jpg',
            price: 7000,
            brand: 'Hua Sheng',
            rating: 3.9,
            numReviews: 5,
            countInStock: 1000
        },
        {
            _id: 10,
            name: 'PVC Pipes',
            category: 'PVC',
            image: './images/pvc pipes.jpg',
            price: 797000,
            brand: 'Lonfa',
            rating: 5.5,
            numReviews: 10,
            countInStock: 120
        },
        {
            _id: 11,
            name: 'Facia boards',
            category: 'PVC',
            image: './images/facia board.jpg',
            price: 70000,
            brand: 'Hua Sheng',
            rating: 3.9,
            numReviews: 5,
            countInStock: 1000
        },
        {
            _id: 12,
            name: 'Hose Pipes',
            category: 'PVC',
            image: './images/horse pipes.jpg',
            price: 500000,
            brand: 'Hua Sheng',
            rating: 4.5,
            numReviews: 21,
            countInStock: 80
        },
        {
            _id: 13,
            name: 'Water Tank',
            category: 'PVC',
            image: './images/water tank.png',
            price: 65000,
            brand: 'Hua Sheng',
            rating: 5,
            numReviews: 101,
            countInStock: 120
        },
        {
            _id: 14,
            name: 'Support',
            category: 'PVC',
            image: './images/support.jpg',
            price: 120000,
            brand: 'Hua Sheng',
            rating: 5,
            numReviews: 120,
            countInStock: 600
        },
        {
            _id: 15,
            name: 'Shelf Brackets',
            category: 'PVC',
            image: './images/shelf brackets.jpg',
            price: 6000,
            brand: 'Hua Sheng',
            rating: 3.5,
            numReviews: 100,
            countInStock: 2000
        },
        {
            _id: 16,
            name: 'HDPE Pipes',
            category: 'PVC',
            image: './images/hdpe.jpg',
            price: 6000,
            brand: 'Hua Sheng',
            rating: 3.5,
            numReviews: 100,
            countInStock: 2000
        },
        {
            _id: 17,
            name: 'Pipe Fittings',
            category: 'PVC',
            image: './images/pipe fittings.jpg',
            price: 55000,
            brand: 'Hua Sheng',
            rating: 5.5,
            numReviews: 10,
            countInStock: 120
        },
        {
            _id: 18,
            name: 'Gutters',
            category: 'PVC',
            image: './images/gutters.jpg',
            price: 7000,
            brand: 'Hua Sheng',
            rating: 3.9,
            numReviews: 5,
            countInStock: 1000
        },
        {
            _id: 19,
            name: 'PVC Pipes',
            category: 'PVC',
            image: './images/pvc pipes.jpg',
            price: 797000,
            brand: 'Lonfa',
            rating: 5.5,
            numReviews: 10,
            countInStock: 120
        },
        {
            _id: 20,
            name: 'Facia boards',
            category: 'PVC',
            image: './images/facia board.jpg',
            price: 70000,
            brand: 'Hua Sheng',
            rating: 3.9,
            numReviews: 5,
            countInStock: 1000
        },
        {
            _id: 21,
            name: 'Hose Pipes',
            category: 'PVC',
            image: './images/horse pipes.jpg',
            price: 500000,
            brand: 'Hua Sheng',
            rating: 4.5,
            numReviews: 21,
            countInStock: 80
        },
        {
            _id: 22,
            name: 'Water Tank',
            category: 'PVC',
            image: './images/water tank.png',
            price: 65000,
            brand: 'Hua Sheng',
            rating: 5,
            numReviews: 101,
            countInStock: 120
        },
        {
            _id: 23,
            name: 'Support',
            category: 'PVC',
            image: './images/support.jpg',
            price: 120000,
            brand: 'Hua Sheng',
            rating: 5,
            numReviews: 120,
            countInStock: 600
        },
        {
            _id: 24,
            name: 'Shelf Brackets',
            category: 'PVC',
            image: './images/shelf brackets.jpg',
            price: 6000,
            brand: 'Hua Sheng',
            rating: 3.5,
            numReviews: 100,
            countInStock: 2000
        },
        {
            _id: 25,
            name: 'HDPE Pipes',
            category: 'PVC',
            image: './images/hdpe.jpg',
            price: 6000,
            brand: 'Hua Sheng',
            rating: 3.5,
            numReviews: 100,
            countInStock: 2000
        },
        {
            _id: 26,
            name: 'Pipe Fittings',
            category: 'PVC',
            image: './images/pipe fittings.jpg',
            price: 55000,
            brand: 'Hua Sheng',
            rating: 5.5,
            numReviews: 10,
            countInStock: 120
        },
        {
            _id: 27,
            name: 'Gutters',
            category: 'PVC',
            image: './images/gutters.jpg',
            price: 7000,
            brand: 'Hua Sheng',
            rating: 3.9,
            numReviews: 5,
            countInStock: 1000
        },
        {
            _id: 28,
            name: 'PVC Pipes',
            category: 'PVC',
            image: './images/pvc pipes.jpg',
            price: 797000,
            brand: 'Lonfa',
            rating: 5.5,
            numReviews: 10,
            countInStock: 120
        },
        {
            _id: 29,
            name: 'Facia boards',
            category: 'PVC',
            image: './images/facia board.jpg',
            price: 70000,
            brand: 'Hua Sheng',
            rating: 3.9,
            numReviews: 5,
            countInStock: 1000
        },
        {
            _id: 30,
            name: 'Hose Pipes',
            category: 'PVC',
            image: './images/horse pipes.jpg',
            price: 500000,
            brand: 'Hua Sheng',
            rating: 4.5,
            numReviews: 21,
            countInStock: 80
        },
        {
            _id: 31,
            name: 'Water Tank',
            category: 'PVC',
            image: './images/water tank.png',
            price: 65000,
            brand: 'Hua Sheng',
            rating: 5,
            numReviews: 101,
            countInStock: 120
        },
        {
            _id: 32,
            name: 'Support',
            category: 'PVC',
            image: './images/support.jpg',
            price: 120000,
            brand: 'Hua Sheng',
            rating: 5,
            numReviews: 120,
            countInStock: 600
        },
        {
            _id: 33,
            name: 'Shelf Brackets',
            category: 'PVC',
            image: './images/shelf brackets.jpg',
            price: 6000,
            brand: 'Hua Sheng',
            rating: 3.5,
            numReviews: 100,
            countInStock: 2000
        },
        {
            _id: 34,
            name: 'HDPE Pipes',
            category: 'PVC',
            image: './images/hdpe.jpg',
            price: 6000,
            brand: 'Hua Sheng',
            rating: 3.5,
            numReviews: 100,
            countInStock: 2000
        },
        {
            _id: 35,
            name: 'Pipe Fittings',
            category: 'PVC',
            image: './images/pipe fittings.jpg',
            price: 55000,
            brand: 'Hua Sheng',
            rating: 5.5,
            numReviews: 10,
            countInStock: 120
        },
        {
            _id: 36,
            name: 'Gutters',
            category: 'PVC',
            image: './images/gutters.jpg',
            price: 7000,
            brand: 'Hua Sheng',
            rating: 3.9,
            numReviews: 5,
            countInStock: 1000
        }
    ]
}